### ISSUE TITLE
The document is not available

### ISSUE THREAD

**Issue by vinh-smartdev** [thecodingmachine/redux-toolkit-wrapper#13]
**Describe the bug**
The document link is not available

**To Reproduce**
1. Go to 'https://thecodingmachine.github.io/react-native-boilerplate/docs/AddAStore#redux-toolkit-wrapper'
2. See error: Page not found

**Expected behavior**
You should see document

**Screenshots**
No

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15
 - Browser: Chrome
 - Version: 94

**Comment by JeremyDolle** [comment]
This project was a part of this [boilerplate](https://github.com/thecodingmachine/react-native-boilerplate) which now use RTKQuery. I copy paste the old documentation into the readme. Thanks for the issue
